name: Sync stage branch with main

on:
  workflow_run:
    workflows: ["ci-release"]
    types:
      - completed


permissions:
  contents: write

jobs:
  sync:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Sync stage to main (fast-forward)
        run: |
          git config user.name  "github-actions"
          git config user.email "actions@users.noreply.github.com"

          git fetch origin main stage

          git checkout stage || git checkout -b stage origin/stage
          git reset --hard origin/main

          git push origin stage --force-with-lease
